apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sec2-ms-controlpanel
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: gcr.io/scalar-e-commerce/sec2-ms-controlpanel
          ports:
            - containerPort: 8080
          command:
            - "pnpm"
          args:
            - "--filter"
            - "ms-controlpanel"
            - "start"
          env:
            - name: CONFIG_YAML
              valueFrom:
                secretKeyRef:
                  name: CONFIG_YAML
                  key: latest
