name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Service Account Key
        run: |
          echo "${{ secrets.GCLOUD_KEY_BASE64 }}" | base64 -di > $HOME/gcloud-key.json

      - name: Save config.yaml
        run: |
          echo "${{ secrets.CONFIG_YAML }}" | base64 -di > config.yaml

      - name: Build and start deployer
        run: |
          docker build --target deployer -t sec2-deployer .
          docker run --privileged --name my-dind-container -d -v ${PWD}:/workspace -v $HOME/gcloud-key.json:/service-account.json  sec2-deployer
      
      - name: Build and Deloy ms-controlpanel
        run: |
          docker exec -it my-dind-container sh -c "node workspace/cli/builder deploy --key-file /service-account.json ms-controlpanel"

      - name: Remove deployer
        run: |
          docker rm -f my-dind-container
