name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Service Account Key
        run: |
          echo "${{ secrets.GCLOUD_KEY_BASE64 }}" | base64 -di > $HOME/gcloud-key.json

      - name: Save config.yaml
        run: |
          echo "${{ secrets.CONFIG_YAML }}" | base64 -di > config.yaml

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: $HOME/gcloud-key.json
          project_id: scalar-e-commerce

      - name: Build ms-cloudpanel
        run: |
          docker build --target ms-controlpanel -t sec2-ms-controlpanel .

      - name: Deploy ms-cloudpanel
        run: |
          gcloud auth configure-docker gcr.io
          gcloud config set project scalar-e-commerce
          docker tag sec2-ms-controlpanel gcr.io/scalar-e-commerce/sec2-ms-controlpanel
          docker push gcr.io/scalar-e-commerce/sec2-ms-controlpanel
          gcloud run deploy sec2-ms-controlpanel \
            --image gcr.io/scalar-e-commerce/sec2-ms-controlpanel \
            --port 8000 \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
